### PR TITLE
fixes https://github.com/kongchen/swagger-maven-plugin/issues/659

### PR DESCRIPTION
**Pull request by martinkalina**

### CODE REVIEW

**Comment by who** [comment]
@martinkalina Thank you for the PR. Could you please add some unit test coverage for this change?

**Comment by martinkalina** [comment]
Hi, I enhanced your tests to cover the change. I had to add Kotlin to the project.

**Comment by who** [comment]
@martinkalina If the Kotlin dependencies are for tests only, could you please add the `test` scope to the dependencies?

**Comment by who** [comment]
Thanks @martinkalina . The scoping change is appreciated.

**Pull request merged**
