### PR TITLE
Yaml output support

### PR DESCRIPTION
**Pull request by mortias**
- Added Yaml output support
 - Fixed some issues related to close the outer BufferedReader(s) that didn't had a close() call

### CODE REVIEW

**Comment by who** [comment]
Hi @mortias , thanks for this contribution - this is great!

Also, thanks for all the whitespace cleanup.

I just merged https://github.com/kongchen/swagger-maven-plugin/pull/240 into master, and now I am seeing some conflicts for this PR.

Please resolve and I'll be happy to merge.

**Comment by mortias** [comment]
You're welcome, can you try again? 
It's because the "extention tests" pr was made on another branch and had some tests included so the expected yaml and json are different afther the merge :)

**Comment by mortias** [comment]
let's say the merge is done, would you mind to run a release?

**Comment by who** [comment]
Thanks for updating the PR - it's merged now!

I am a contributor/comitter on this codebase, but only @kongchen has permissions to push releases and snapshots.

@kongchen *ping*  Do you think we should release `3.1.1-SNAPSHOT` as `3.1.1-RELEASE` and bump the snapshot version to `3.1.2-SNAPSHOT` ?

**Comment by mortias** [comment]
Perfect, ty

**Comment by sofianh** [comment]
This is exactly what I'm looking for. Is it merged to any release branches yet?
I tried 3.1.2 and 3.1.4, but no yaml being generated.

**Pull request merged**
