### PR TITLE
Uprade swagger-core to 1.5.20 to pickup bug fix

### PR DESCRIPTION
**Pull request by dantran**
https://github.com/swagger-api/swagger-core/issues/2707

### CODE REVIEW

**Comment by Postremus** [comment]
Please fix the now failing tests. See the travis-ci log.

**Comment by who** [comment]
@dantran This PR is causing test failures. These failures must be fixed before the PR can be considered.

**Comment by dantran** [comment]
sorry about the noise,  i need to decline this PR due to time constraint

**Comment by Postremus** [comment]
The failing tests look like they are related to the issue https://github.com/swagger-api/swagger-parser/issues/772.

@dantran I would love to take on these issues, and finalize the PR, with your OK?

**Pull request closed without merging**
