### PR TITLE
Remove basePath from path beginning

### PR DESCRIPTION
**Pull request by artkoshelev**
Trivial change to remove basePath part from endpoint path

### CODE REVIEW

**Comment by artkoshelev** [comment]
It looks like a bug for me - why path in swagger definition should contain `basePath` part? What's the purpose of having `basePath` at all then? If user don't need replacement, she could set `basePath` to empty string.

**Comment by artkoshelev** [comment]
@who can you merge it and release new version please? or if you insist on hiding it behind option, i'll do this.

**Comment by artkoshelev** [comment]
@who ping

**Comment by who** [comment]
@artkoshelev Does this issue exist when using swagger-core on its own ? I'm trying to figure out if this is a problem with swagger-maven-plugin, or if it's a problem with upstream swagger-core.

**Comment by artkoshelev** [comment]
swagger-core implements same behavior, but swagger-maven-plugin not using swagger-core here.

**Comment by artkoshelev** [comment]
@who i've added option to enable this feature, it would be disabled by default

**Comment by artkoshelev** [comment]
ping @who

**Comment by who** [comment]
@artkoshelev Please resolve conflicts and I can merge this PR.

**Comment by artkoshelev** [comment]
@who conflicts resolved

**Pull request merged**
