### PR TITLE
Fix kongchen/swagger-maven-plugin#347

### PR DESCRIPTION
**Pull request by proshin-roman**
This pull request fixes an issue, that was described in the ticket #347. As well I added a new test to cover the described case.

### CODE REVIEW

**Comment by ThomasSolti** [comment]
please merge this fix.

**Comment by who** [comment]
Thanks for your contribution, @proshin-roman !


Ping @kongchen , we should release a new version soon.

**Comment by ThomasSolti** [comment]
Ping @kongchen , when can we expect this fix to be released?

**Comment by proshin-roman** [comment]
Yeah, @kongchen please release the fixed version - I need some fixes in my project.

**Pull request merged**
