### PR TITLE
Resolves #207: Use @Info annotation instead of <info> in plugin configuration

### LINKED ISSUE #207: Use @Info annotation instead of <info> in plugin configuration
I'm new to using Swagger and using this plugin, so forgive me if I'm mistaken.  From what I understand, at the moment, the plugin requires Info as part of the configuration.  Are there any plans to have this information parsed directly from the @Info annotation inside the @SwaggerDefinition annotation instead (or at least the option to do it this way)?

### PR DESCRIPTION
**Pull request by AlexElin**
This resolves #207. Also it relates to #221
Also I did some cleanup of the source code.

### CODE REVIEW

**Comment by fraulyoner** [comment]
I'm really looking forward to this merge! :) We would benefit from this extension since we normally use the `@Info` annotation and want to avoid duplicating this information in the `pom.xml`

**Comment by who** [comment]
@AlexElin Thank you very much for this contribution, and for taking the time to clean up the code formatting.

**Comment by fraulyoner** [comment]
Thank you for both, contributing and merging!

**Comment by attilagenc** [comment]
Merge is not complete. Still getting error on v3.1.4

Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.4:generate (default) on project bas: `<info><title>` is required by Swagger Spec. -> [Help 1]

**Comment by mykolapolonskyi** [comment]
Hello @attilagenc 
I have thougth that issue still accutal but I checked version 3.1.4 (after updating from 3.1.2) and it works withoud <info> block. 
Please check your version and before generating *swagger.json* use `mvn clean` and recompile needed classes - it helps me from time to time.

**Comment by CK50** [comment]
Hello @attilagenc, hello @mykolapolonskyi, @fraulyoner,

like @fraulyoner I am also trying to remove doc duplication from pom.xml. But using 3.1.4 I am also struggling with 

```
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.4:generate (default) on project dicloud-metadata-service: `<info><title>` is required by Swagger Spec.
```

This occurs when I uncomment the tag `info` from pom.xml:

```
<configuration>
    <apiSources>
        <apiSource>
            <springmvc>false</springmvc>
            <locations>my.package.myResourceClass</locations>
            <basePath>/</basePath>
            <info>
                <title>My Title</title>
            </info>
        </apiSource>
    </apiSources>
</configuration>
```

fyi1, in case it matters,
my Java resource contains:

```
@SwaggerDefinition( info = @Info(
    title = "some API title", 
    description = "some API description", version = "1.0"), 
    tags = {@Tag(name="Tasks",description = "some tag desc")}
)
```

fyi2,
I have forked swagger-maven-plugin and have built the 3.1.4 jar locally and see the same problem.

fyi3, in case this helps,
ApiDocumentMojo.java:138 (3.1.4) contains:
```
        if (apiSource.getInfo().getTitle() == null) {
            throw new GenerateException("`<info><title>` is required by Swagger Spec.");
        }
```

If anybody can confirm that `<apiSource><info>` is really optional in 3.1.4, this would help a lot. - If optional, any hints of what I am doing wrong here would be much appreciated.

----

The other thing I am having trouble with since switching from 3.1.3 to 3.1.4 is:

`[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.4:generate (default) on project abc: 
Execution default of goal com.github.kongchen:swagger-maven-plugin:3.1.4:generate failed: 
Plugin com.github.kongchen:swagger-maven-plugin:3.1.4 or one of its dependencies could not be resolved: 
Could not find artifact org.apache.commons:commons-lang3:jar:3.6-SNAPSHOT -> [Help 1]`

I have no clue why maven would be looking for commons-lang3:jar:3.6-SNAPSHOT.

This problem does not occur in 3.1.3 and can be "fixed" by changing swagger-maven-plugin: pom.xml from
`<commons-lang3.version>[3.4,4.0)</commons-lang3.version>`
to
`<commons-lang3.version>3.4</commons-lang3.version>`

If anybody has an ideas, I'd be very interested. If I should file a bug, please let me know.

**Comment by mykolapolonskyi** [comment]
@CK50 regarding your comment - If snapshot status isn't critical  for you pls try 3.1.5-snapshot in your project. for both cases.

**Pull request merged**
